<#
  bro-improvement-planner.ps1 — L5 self-improvement planner (Phase 8b) · DETERMINISTIC · PROPOSE-ONLY
  EN: Reads the current OPEN_ITEMS (from bro-selfcheck) + the failure ledger and writes a BOUNDED set of change-request
      proposals to change-requests/CR_PROPOSALS.md. Each proposal is an execution package (what · why · files affected ·
      risk · REQUIRES GEV APPROVAL · verification plan). It PROPOSES, it NEVER applies — no law/spine/skill/memory
      mutation, no LLM, no cron. Deterministic content (keyed by open-item id + first_seen) so a daily re-run does not
      dirty the tree unless the open-item set changes. D0 + _core/production_os/SELF_IMPROVEMENT.md.
  HY: Կարդում է OPEN_ITEMS + failure ledger ու գրում bounded change-request proposal-ներ։ ԱՌԱՋԱՐԿՈՒՄ Է, ԵՐԲԵՔ չի
      կիրառում (ոչ law/spine/skill/memory, ոչ LLM, ոչ cron)։ Deterministic content՝ daily re-run tree չի կեղտոտում։
  Exit: 0 (always — proposing is not a pass/fail gate; the report shows how many proposals).
#>
$ErrorActionPreference = 'Stop'
Set-Location -Path (Join-Path $PSScriptRoot '..\..')
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}

# canned, deterministic fix package per known open-item id (proposal only)
function Get-Proposal($id, $desc) {
  switch -Regex ($id) {
    'OI-CONTENT-HASH'  { @{ fix='Re-stamp the content baseline: pwsh tools/checks/bro-content-hash-check.ps1 -Stamp -Execute -Yes'; files='bro.manifest.json'; risk='LOW (metadata only; snapshot to _before)'; verify='content-hash MATCH; audit GREEN' } }
    'OI-PROJECT-RED'   { @{ fix='Run bro-project-doctor/audit for the failing project; if registry lag, re-run the fixed bro-update-spine; else investigate.'; files='memory/_own/registry.json (via governed tool only)'; risk='MED (touches a project bro spine — governed tool, gitignored infra)'; verify='project-doctor + audit GREEN' } }
    'OI-DOC-REFS'      { @{ fix='Fix the broken link / duplicate law-id reported by bro-refs-check.'; files='the offending .md file(s)'; risk='LOW (doc edit)'; verify='bro-refs-check GREEN' } }
    'OI-L2-BEHAVIORAL' { @{ fix='Phase 8d: build tools/checks/bro-behavior-eval.ps1 + evals/cases (L0 bilingual, proof-or-label, no-fake-GREEN, anti-flattery, freshness, uncertainty, D0-refusal). LLM, weekly/on-demand.'; files='tools/checks/bro-behavior-eval.ps1, evals/cases/*'; risk='MED (LLM non-determinism; keep OUT of daily deterministic path)'; verify='harness runs or names LLM-blocked YELLOW (never fake GREEN)' } }
    'OI-L3-PRODUCTION' { @{ fix='Phase 8c: build tools/checks/bro-production-check.ps1 (production_os presence, PROVEN/DECLARED label consistency, ledger freshness, UI-proof reference). Weekly UI smoke stub (no fake runtime).'; files='tools/checks/bro-production-check.ps1'; risk='LOW static; UI smoke needs sandbox (weekly)'; verify='static checks run; smoke named-blocked if no sandbox' } }
    'OI-L4-TASTE'      { @{ fix='Phase 8d: build tools/checks/bro-taste-check.ps1 (Gev Taste Engine filled, GOOD/BAD used, repeated-mistake scan of FAILURE_LEDGER/NEVER_REPEAT).'; files='tools/checks/bro-taste-check.ps1, evals/cases/*'; risk='MED (quality grading needs LLM; keep weekly)'; verify='static taste checks GREEN; LLM grading weekly/named-blocked' } }
    'OI-ORPHAN-SCAN'   { @{ fix='Extend bro-refs-check with orphan/dead-doc detection (a .md linked from no other .md).'; files='tools/checks/bro-refs-check.ps1'; risk='LOW (read-only scan; tune to avoid false positives)'; verify='orphan list reported; no false positives on known-referenced docs' } }
    default            { @{ fix="Investigate and resolve: $desc"; files='(TBD)'; risk='(assess)'; verify='(define)' } }
  }
}

# parse current open items from the selfcheck carry-forward ledger
$oiPath = 'logs/OPEN_ITEMS.md'
$open = @()
if (Test-Path $oiPath) {
  foreach ($ln in Get-Content $oiPath) {
    $m = [regex]::Match($ln, '\[(OI-[A-Z0-9-]+)\]\s+sev=(\w+)\s+first=(\d{4}-\d{2}-\d{2})\s+status=OPEN\s+—\s+(.+)$')
    if ($m.Success) { $open += [pscustomobject]@{ id=$m.Groups[1].Value; sev=$m.Groups[2].Value; first=$m.Groups[3].Value; desc=$m.Groups[4].Value } }
  }
}
# bound: HIGH first, then MED, then LOW; cap at 8
$order = @{ HIGH=0; MED=1; LOW=2 }
$open = @($open | Sort-Object { $order["$($_.sev)"] }, id | Select-Object -First 8)

$lines = @(
  '# CHANGE-REQUEST PROPOSALS — L5 Improvement Planner (PROPOSE-ONLY) / Փոփոխության առաջարկներ',
  '',
  '> **EN:** Auto-generated by tools/checks/bro-improvement-planner.ps1 from the current OPEN_ITEMS + failure ledger.',
  '> Deterministic (keyed by open-item id). **PROPOSAL ONLY — Bro NEVER applies these. Each REQUIRES GEV APPROVAL**',
  '> (D0 + _core/production_os/SELF_IMPROVEMENT.md). Applying any of these needs your explicit command + token.',
  '> **HY:** Ավտո-գեներացված. **ՄԻԱՅՆ ԱՌԱՋԱՐԿ — Bro-ն ԵՐԲԵՔ չի կիրառում. ամեն մեկը ՊԱՀԱՆՋՈՒՄ Է ԳԵՎԻ ՀԱՍՏԱՏՈՒՄ (D0)։**',
  '',
  "proposals: $($open.Count) (bounded)"
)
$n = 0
foreach ($it in $open) {
  $n++
  $p = Get-Proposal $it.id $it.desc
  $lines += @(
    '',
    "## CR-$('{0:D3}' -f $n) — [$($it.id)] sev=$($it.sev) (open since $($it.first))",
    "- **What:** $($it.desc)",
    "- **Proposed fix:** $($p.fix)",
    "- **Files affected:** $($p.files)",
    "- **Risk:** $($p.risk)",
    "- **Verification plan:** $($p.verify)",
    "- **Approval:** ⛔ REQUIRES GEV APPROVAL — Bro will NOT apply this autonomously."
  )
}
if ($open.Count -eq 0) { $lines += @('', '_No open items — no proposals. (Clean.)_') }
Set-Content -Path 'change-requests/CR_PROPOSALS.md' -Value $lines -Encoding utf8

"bro-improvement-planner - PROPOSE-ONLY (D0) / ՄԻԱՅՆ ԱՌԱՋԱՐԿ"
"  open items read: $($open.Count)  ->  proposals written: $n  (change-requests/CR_PROPOSALS.md)"
"  NOTE: proposals only — nothing applied; each requires Gev approval."
"RESULT: GREEN (proposals generated; no changes applied)"
exit 0
