<#
  bro-install.ps1 — INSTALL PROJECT BRO (DRY-RUN ONLY, clean-build Phase 3, §7 / D0)
  EN: Rollout command in DRY mode: shows the X/bro skeleton it WOULD create from tools/templates/project-bro/
      and EXECUTES NOTHING. Creates no Project Bro, touches no project folder, pulls no release. Real execution is
      a LATER, Gev-gated Rollout step.
  HY: Rollout command DRY mode-ում՝ ցույց է տալիս X/bro skeleton-ը, որ ԿՍՏԵՂԾԵՐ template-ից, ու ՈՉԻՆՉ ՉԻ ԿԱՏԱՐՈՒՄ։
      Ոչ Project Bro, ոչ project folder, ոչ pull։ Real execution-ը հետագա Gev-gated Rollout է։
  Exit: 0 dry-preview OK · 2 missing inputs.
#>
param(
  [string]$ProjectId = '',
  [string]$ProjectPath = '',
  [switch]$Yes
)
$ErrorActionPreference = 'Stop'
Set-Location -Path (Join-Path $PSScriptRoot '..')

"INSTALL PROJECT BRO - DRY-RUN (clean build) - executes nothing, creates no Project Bro"
if (-not $ProjectId -or -not $ProjectPath) {
  "  usage: bro-install.ps1 -ProjectId <id> -ProjectPath <abs-path>"
  exit 2
}
$tmpl = 'tools/templates/project-bro'
$tmplOk = Test-Path $tmpl
"  template source: $tmpl  (present: $tmplOk)"
"  preview - X/bro skeleton that WOULD be created at: $ProjectPath\bro\"
"    spine/                 <- local copy of an approved spine release (pull/verify/stamp, Phase 4)"
"    memory/                <- sealed $ProjectId memory (the only unique part, B1/B4/L8)"
"    logs/                  <- session/action/memory-write/local-audit/hook-blocks/errors"
"    bro.manifest.json      <- from bro.manifest.template.json (placeholders filled)"
"    health.report.md       <- generated by the local doctor"
"  preconditions (real run): project REGISTERED first; an approved spine release available to pull"
if ($Yes) { "  (YES received)" }
"  DRY-RUN: nothing executed. No X/bro created. No project folder touched. No release pulled."
"  next: real INSTALL is a later Gev-gated Rollout step (requires BRO_GEV_APPROVED=1 + Gev command)."
exit 0
